[[work-experience-short]]
== icon:file-text[] Work Experience

[cols="1,1,4,1", options="noheader", stripes=odd]
|===
| icon:calendar[] *Oct 2017*
| icon:calendar[] *Current*
| <<#Philips,*Software Architect Cloud & Platforms*>>
| *Philips Research*

4+| Defining and implementing *cloud (native) architectures _(based on Amazon AWS)_* for various *research projects & products* while *ensuring organizational compliance* for global research/product groups. Ensuring that code and deliverables are of high quality with security mitigation's. *_Evangelizing best practice software engineering principles_* across the entire (global) organization.

| icon:calendar[] *Oct 2013*
| icon:calendar[] *Oct 2017*
| <<#Signify,*Software Architect Cloud & Platforms*>>
| *Signify*

4+| Responsible for the design and implementation of a *_global Cloud based product platform (based on Amazon AWS)_* (architecture and implementation). Ensuring that implemented polyglot microservices are used in *_multiple product propositions_*.

| icon:calendar[] *Dec 2008*
| icon:calendar[] *Oct 2013*
| <<#IHomer,*Software Engineer & Architect EV Solutions*>>
| *IHomer*

4+| Responsible for design & implementation of a *_global web-based platform to facilitate charging of electrical vehicles_*.

| icon:calendar[] *Sept 1997*
| icon:calendar[] *Dec 2008*
| <<#Cgi,*Software Engineer/Competence Lead*>>
| *CGI*

4+| Implementation of different *_mobile applications, infrastructures and technologies and professional/people development_* for a group of +/- 200 software engineers.

| icon:calendar[] *Nov 1995*
| icon:calendar[] *Sept 1997*
| <<#JanDeRijk,*Internal IT support*>>
| *Jan de Rijk Logistics*

4+| Implementation of internal projects, including *_transport planning, vehicle track and trace_*.
|===